---
title: | 
    | Exercise: Potential Outcomes Model (Solutions)
author: "Ryan T. Moore"
date: '2026-07-21'
documentclass: article
format:
  pdf:
    geometry: 
      - top=2cm
    number_sections: false
    toc: false
header-includes:
  - \usepackage{amsmath}
  - \usepackage{bm}
---

```{r}
#| label: setup
#| include: false

knitr::opts_chunk$set(echo = TRUE)
```

Suppose a political party wants to estimate the effect of introducing a **new voter registration system** on voter turnout. The registration system will make it easier to register and will highlight the upcoming election, in hopes of increasing turnout. The party randomly selects 3 out of 6 local villages in which to introduce the system. After the election, they compare villages with the new system to the old system. Let the new registration system be the treatment ($T=1$), and the old system be the control ($T=0$). For village $i$, the observed outcome is $Y_i(T_i)$, the turnout percentage.


| Village | System | Turnout (%) | $Y_i(1)$        | $Y_i(0)$        |
| :-----: | :----: | :---------: | :-------------: | :-------------: |
|    A    |  New   |     40      | **40** | $\qquad \qquad \qquad$ |
| | | | | |
|    B    |  New   |     50      |    **50**             |                 |
| | | | | |
|    C    |  Old   |     50      |    $\qquad \qquad \qquad$             |    **50**             |
| | | | | |
|    D    |  New   |     30      |       **30**          |                 |
| | | | | |
|    E    |  Old   |     30      |                 |  **30**               |
| | | | | |
|    F    |  Old   |     70      |                 |  **70**               |
| | | | | |

Table: Experiment 1; treatment assignments and turnout percentages for 6 villages. \label{t:y1y0}

## Part 1

1. In Table \ref{t:y1y0}, fill in any information we know from this experiment.  

2. What is the "fundamental problem of causal inference"? Describe it in the _substantive_ terms of the political example here.

**For any village at a moment in time, we can never observe its turnout under both the new and the old system.**

\vspace{.5in}

3. Calculate an estimate of the experiment's average treatment effect -- the difference between the average turnout in treated versus control villages. Substantively, did the new program appear to meet its goal?

$$\mathbf{\frac{40+50+30}{3} - \frac{50+30+70}{3} = 40 - 50 = -10}$$

**No, the program does not appear to meet its goal.**

\vspace{.5in}


## Part 2

Suppose the party conducts the experiment again in a subsequent electoral cycle. Somehow, you know for certain what would happen in every village under both the new and old systems. Table \ref{t:yobs} contains the full set of potential outcomes from this 2nd experiment.  

| Village | System | $Y_i(1)$ | $Y_i(0)$ | $Y_i^{obs}$       |
| :-----: | :----: | :------: | :------: | --------------- |
|    G    |  Old   |    20    |    40    | **40** |
||||||
|    H    |  New   |    60    |    50    |  **60**               |
||||||
|    I    |  Old   |    70    |    70    | **70**                 |
||||||
|    J    |  New   |    40    |    60    |  **40**               |
||||||
|    K    |  New   |    100    |    10    | **100**                |
||||||
|    L    |  Old   |    80    |    80    |  **80**               |
||||||

Table: Experiment 2; treatment assignments and turnout percentages for 6 other villages.  \label{t:yobs}

4.  Fill out the empty column of observed outcomes in Table \ref{t:yobs}.

5.  What is the true treatment effect of the new registration system in Village G?

$$\tau_G \mathbf{= 20-40 = -20}$$

\vspace{.1in}

6.  What is the true treatment effect of the new registration system in Village L?

$$\tau_L \mathbf{= 80-80 = 0}$$


\vspace{.1in}


## Part 3

Consider only the first four villages of Part 1. Assume a constant 
$\tau_i = 10 \quad \forall i$ and complete the table below.

| Village | System | Turnout (%) | $Y_i(1)$        | $Y_i(0)$        |
| :-----: | :----: | :---------: | :-------------: | :-------------: |
|    A    |  New   |     40      | **40**  | **30**  |
| | | | | |
|    B    |  New   |     50      |  **50**               |  **40**               |
| | | | | |
|    C    |  Old   |     50      |  **60**               |  **50**               |
| | | | | |
|    D    |  Old   |     30      |   **40**              |  **30**               |
| | | | | |

7. How many assignments of 2 villages to each system could there be?

$$\mathbf{\binom{4}{2}} \mathbf{= \frac{4!}{2!2!} = \frac{4\cdot 3 \cdot 2}{2 \cdot 2} = 6}$$

\vspace{.1in}

8. Calculate the empirical $\widehat{ATE}$ for each of those assignments.

| Treated Units | $\widehat{ATE}$ |
| :-: | :-: |
| AB | 5 |
| AC | 15 |
| AD | -5 |
| BC | 25 |
| BD | 5 |
| CD | 15 |


\vspace{.1in}

9. Calculate the mean of those $\widehat{ATE}$ values, and comment.

**The mean of the $\widehat{ATE}$ values is**

$$\mathbf{\frac{5 + 15 - 5 + 25 + 5 + 15}{6} = 10}$$

**The true average treatment effect is also 10. We have shown that the difference in means is unbiased for the true treatment effect under random allocation of two units to treatment, two to control.**